default: &default
  adapter: postgresql
  encoding: unicode
  username: kana_champion
  password: <%= ENV["KANA_CHAMPION_DATABASE_PASSWORD"] %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["KANA_CHAMPION_DATABASE_HOST"] || "localhost" %>

development:
  <<: *default
  database: kana_champion_development

test:
  <<: *default
  database: kana_champion_test

production:
  primary: &primary_production
    <<: *default
    database: kana_champion_production


#  cache:
#    <<: *primary_production
#    database: kana_champion_production_cache
#    migrations_paths: db/cache_migrate
#  queue:
#    <<: *primary_production
#    database: kana_champion_production_queue
#    migrations_paths: db/queue_migrate
#  cable:
#    <<: *primary_production
#    database: kana_champion_production_cable
#    migrations_paths: db/cable_migrate}
